import {
    DEFAULT_FEATURE_SEARCH_LABEL_BACKGROUND_COLOR,
    FeatureSearchColorMode,
    FeatureSearchGeometryKind,
    FeatureSearchRuleFilter,
    FeatureSearchStyleRule
} from "../shared/feature-search-state";
import {
    defaultSearchStyleColorDraft,
    DEFAULT_SEARCH_STYLE_SOLID_COLOR,
    gradientStopsToDraft,
    isNumericStyleValueKind,
    normalizeHexColor,
    SearchStyleCategoryStopDraft,
    SearchStyleColorDraft,
    SearchStyleFieldOption,
    SearchStyleFieldValueKind,
    serializableCategoryStops,
    serializableGradientStops
} from "./search-style-color.util";

export interface FeatureSearchStyleFilterDraft {
    id: number;
    attributeField: string;
    customExpression?: boolean;
    operator: string;
    filterValue: unknown;
}

export interface FeatureSearchStyleRuleDraft {
    id: number;
    name: string;
    autoGenerated?: boolean;
    filters: FeatureSearchStyleFilterDraft[];
    visualization: FeatureSearchGeometryKind;
    lineWidth: number;
    pointRadius?: number;
    opacity: number;
    labelExpression: string;
    labelCustomExpression?: boolean;
    labelBackgroundColor: string;
    color: SearchStyleColorDraft;
}

/** Stateful ID allocator and lossless adapter between canonical rules and reusable editor drafts. */
export class SearchStyleRuleDraftCodec {
    private nextRuleId = 1;
    private nextConditionId = 1;
    private nextColorStopId = 1;

    constructor(private fieldOptions: readonly SearchStyleFieldOption[] = []) {
    }

    /** Updates optional schema hints without changing existing drafts. */
    setFieldOptions(fieldOptions: readonly SearchStyleFieldOption[]): void {
        this.fieldOptions = fieldOptions;
    }

    /** Resets generated editor identities before replacing the complete draft list. */
    reset(): void {
        this.nextRuleId = 1;
        this.nextConditionId = 1;
        this.nextColorStopId = 1;
    }

    /** Advances generated identities beyond all identities in an externally supplied draft list. */
    synchronizeIds(drafts: readonly FeatureSearchStyleRuleDraft[]): void {
        this.nextRuleId = Math.max(this.nextRuleId, ...drafts.map(rule => rule.id + 1), 1);
        this.nextConditionId = Math.max(
            this.nextConditionId,
            ...drafts.flatMap(rule => rule.filters.map(filter => filter.id + 1)),
            1
        );
        this.nextColorStopId = Math.max(
            this.nextColorStopId,
            ...drafts.flatMap(rule => [
                ...rule.color.gradientStops.map(stop => stop.id + 1),
                ...rule.color.categoryStops.map(stop => stop.id + 1)
            ]),
            1
        );
    }

    /** Converts canonical rules into independent editor drafts. */
    toDrafts(rules: readonly FeatureSearchStyleRule[]): FeatureSearchStyleRuleDraft[] {
        this.reset();
        return rules.map(rule => this.toDraft(rule));
    }

    /** Converts independent editor drafts back into canonical high-fidelity rules. */
    fromDrafts(drafts: readonly FeatureSearchStyleRuleDraft[]): FeatureSearchStyleRule[] {
        return drafts.map(rule => this.fromDraft(rule));
    }

    /** Creates a new default rule using schema hints only when they are available. */
    createRule(id = this.nextRuleId++): FeatureSearchStyleRuleDraft {
        const fieldOption = this.defaultFieldOption();
        const field = fieldOption?.value ?? "";
        const color = defaultSearchStyleColorDraft(field);
        if (fieldOption?.valueKind === "enum") {
            color.mode = "categories";
        } else if (!isNumericStyleValueKind(fieldOption?.valueKind)) {
            color.mode = "solid";
        }
        return {
            id,
            name: "",
            filters: [],
            visualization: "any",
            lineWidth: 5,
            pointRadius: 7.5,
            opacity: 60,
            labelExpression: field,
            labelCustomExpression: false,
            labelBackgroundColor: DEFAULT_FEATURE_SEARCH_LABEL_BACKGROUND_COLOR,
            color
        };
    }

    /** Creates one default filter condition for the current optional schema context. */
    createFilter(): FeatureSearchStyleFilterDraft {
        const field = this.defaultFieldOption()?.value ?? "";
        const option = this.fieldOption(field);
        return {
            id: this.nextConditionId++,
            attributeField: field,
            customExpression: false,
            operator: isNumericStyleValueKind(option?.valueKind) ? ">" : "=",
            filterValue: isNumericStyleValueKind(option?.valueKind)
                ? 80
                : option?.enumValues?.[0] ?? ""
        };
    }

    /** Deep-copies drafts while retaining transient editor identities. */
    cloneDrafts(drafts: readonly FeatureSearchStyleRuleDraft[]): FeatureSearchStyleRuleDraft[] {
        return drafts.map(rule => ({
            ...rule,
            filters: rule.filters.map(filter => ({...filter})),
            color: {
                ...rule.color,
                gradientStops: rule.color.gradientStops.map(stop => ({...stop})),
                categoryStops: rule.color.categoryStops.map(stop => ({...stop}))
            }
        }));
    }

    /** Serializes one UI draft into the canonical JSON rule shape. */
    private fromDraft(rule: FeatureSearchStyleRuleDraft): FeatureSearchStyleRule {
        const geometry = this.geometry(rule.visualization);
        const width = clamp(rule.lineWidth, 1, geometry === "label" ? 96 : 32, 4);
        return {
            ...(rule.name.trim() ? {name: rule.name.trim()} : {}),
            ...(rule.autoGenerated ? {autoGenerated: true} : {}),
            geometry,
            filter: rule.filters
                .filter(filter => !!filter.attributeField.trim())
                .map(filter => this.filterFromDraft(filter)),
            color: this.colorFromDraft(rule.color),
            width,
            ...(rule.pointRadius === undefined
                ? {}
                : {pointRadius: clamp(rule.pointRadius, 0, 128, Math.max(3, width * 1.5))}),
            opacity: clamp(rule.opacity, 0, 100, 100) / 100,
            ...(geometry === "label" && rule.labelExpression.trim()
                ? {labelExpression: rule.labelExpression.trim()}
                : {}),
            ...(geometry === "label" && rule.labelCustomExpression ? {labelCustomExpression: true} : {}),
            ...(geometry === "label"
                ? {labelBackgroundColor: normalizeHexColor(
                    rule.labelBackgroundColor,
                    DEFAULT_FEATURE_SEARCH_LABEL_BACKGROUND_COLOR)}
                : {})
        };
    }

    /** Loads one canonical JSON rule without collapsing geometry or expression flags. */
    private toDraft(rule: FeatureSearchStyleRule): FeatureSearchStyleRuleDraft {
        const geometry = this.geometry(rule.geometry);
        const width = clamp(
            rule.width,
            1,
            geometry === "label" ? 96 : 32,
            geometry === "label" ? 22 : 4
        );
        return {
            id: this.nextRuleId++,
            name: rule.name ?? "",
            autoGenerated: !!rule.autoGenerated,
            filters: rule.filter.map(filter => this.filterToDraft(filter)),
            visualization: geometry,
            lineWidth: width,
            pointRadius: rule.pointRadius === undefined
                ? undefined
                : clamp(rule.pointRadius, 0, 128, Math.max(3, width * 1.5)),
            opacity: clamp((rule.opacity ?? 1) * 100, 0, 100, 100),
            labelExpression: rule.labelExpression ?? this.defaultFieldOption()?.value ?? "",
            labelCustomExpression: !!rule.labelCustomExpression,
            labelBackgroundColor: normalizeHexColor(
                rule.labelBackgroundColor,
                DEFAULT_FEATURE_SEARCH_LABEL_BACKGROUND_COLOR),
            color: this.colorToDraft(rule.color)
        };
    }

    /** Serializes one structured or custom filter draft. */
    private filterFromDraft(filter: FeatureSearchStyleFilterDraft): FeatureSearchRuleFilter {
        if (filter.customExpression) {
            return {
                field: filter.attributeField,
                op: "=",
                value: true,
                customExpression: true
            };
        }
        return {
            field: filter.attributeField,
            op: filter.operator,
            value: this.filterValue(filter)
        };
    }

    /** Loads one filter and performs the bounded legacy custom-expression inference. */
    private filterToDraft(filter: FeatureSearchRuleFilter): FeatureSearchStyleFilterDraft {
        const legacyCustomExpression = filter.customExpression === undefined
            && this.fieldOptions.length > 0
            && filter.op === "="
            && filter.value === true
            && !this.fieldOption(filter.field);
        return {
            id: this.nextConditionId++,
            attributeField: filter.field,
            customExpression: !!filter.customExpression || legacyCustomExpression,
            operator: filter.op || "=",
            filterValue: filter.value ?? ""
        };
    }

    /** Serializes color controls without schema-driven rewrites when schema is absent. */
    private colorFromDraft(color: SearchStyleColorDraft): FeatureSearchColorMode {
        const fallbackColor = normalizeHexColor(color.fallbackColor, color.solidColor);
        if (color.mode === "solid") {
            return {mode: "solid", color: normalizeHexColor(color.solidColor)};
        }
        if (color.mode === "categories") {
            return {
                mode: "categories",
                field: color.field,
                ...(color.customField ? {customField: true} : {}),
                stops: serializableCategoryStops(
                    color,
                    this.fieldOption(color.field)?.valueKind ?? color.categoryValueKind),
                fallbackColor
            };
        }
        const option = this.fieldOption(color.field);
        if (!color.customField && option && !isNumericStyleValueKind(option.valueKind)) {
            return {
                mode: "categories",
                field: color.field,
                stops: serializableCategoryStops(color, option.valueKind),
                fallbackColor
            };
        }
        return {
            mode: "gradient",
            field: color.field,
            ...(color.customField ? {customField: true} : {}),
            stops: serializableGradientStops(color) ?? [],
            fallbackColor
        };
    }

    /** Loads a canonical color union while retaining custom-field intent and typed stops. */
    private colorToDraft(color: FeatureSearchColorMode): SearchStyleColorDraft {
        const field = color.mode === "solid"
            ? this.defaultFieldOption()?.value ?? ""
            : color.field;
        const draft = defaultSearchStyleColorDraft(field);
        if (color.mode === "solid") {
            const solidColor = normalizeHexColor(color.color, DEFAULT_SEARCH_STYLE_SOLID_COLOR);
            return {...draft, mode: "solid", solidColor, fallbackColor: solidColor};
        }
        const fallbackColor = normalizeHexColor(color.fallbackColor, DEFAULT_SEARCH_STYLE_SOLID_COLOR);
        if (color.mode === "categories") {
            return {
                ...draft,
                mode: "categories",
                field,
                customField: !!color.customField,
                categoryValueKind: categoryValueKind(color.stops),
                solidColor: fallbackColor,
                fallbackColor,
                categoryStops: color.stops.map(stop => categoryStopToDraft(stop, this.nextColorStopId++))
            };
        }
        return {
            ...draft,
            mode: "gradient",
            field,
            customField: !!color.customField,
            solidColor: fallbackColor,
            fallbackColor,
            gradientStops: gradientStopsToDraft(color.stops, () => this.nextColorStopId++)
        };
    }

    /** Applies optional schema scalar coercion to one filter value. */
    private filterValue(filter: FeatureSearchStyleFilterDraft): unknown {
        const valueKind = this.fieldOption(filter.attributeField)?.valueKind;
        if (isNumericStyleValueKind(valueKind)) {
            const numeric = Number(filter.filterValue);
            return Number.isFinite(numeric) ? numeric : filter.filterValue;
        }
        if (valueKind === "boolean") {
            const value = String(filter.filterValue ?? "").trim().toLowerCase();
            if (value === "true" || value === "false") {
                return value === "true";
            }
        }
        return typeof filter.filterValue === "string"
            ? filter.filterValue
            : String(filter.filterValue ?? "");
    }

    /** Resolves optional transient schema metadata for a field. */
    private fieldOption(field: string): SearchStyleFieldOption | undefined {
        return this.fieldOptions.find(option => option.value === field);
    }

    /** Returns the first scalar field offered by the transient host context. */
    private defaultFieldOption(): SearchStyleFieldOption | undefined {
        return this.fieldOptions.find(option =>
            option.valueKind !== "object" && option.valueKind !== "array");
    }

    /** Validates a persisted or UI geometry identifier. */
    private geometry(value: string | undefined): FeatureSearchGeometryKind {
        return ["any", "point", "line", "surface", "polygon", "mesh", "label"].includes(value ?? "")
            ? value as FeatureSearchGeometryKind
            : "any";
    }
}

function categoryStopToDraft(
    stop: {value: unknown; color: string},
    id: number
): SearchStyleCategoryStopDraft {
    const valueText = stop.value === null || stop.value === undefined ? "" : String(stop.value);
    return {
        id,
        valueText,
        color: normalizeHexColor(stop.color, DEFAULT_SEARCH_STYLE_SOLID_COLOR),
        pending: valueText.trim().length === 0
    };
}

function categoryValueKind(stops: Array<{value: unknown}>): SearchStyleFieldValueKind | undefined {
    const types = new Set(stops.map(stop => typeof stop.value));
    if (types.size !== 1) {
        return undefined;
    }
    const type = types.values().next().value;
    return type === "number" || type === "boolean" || type === "string"
        ? type
        : undefined;
}

function clamp(value: unknown, minimum: number, maximum: number, fallback: number): number {
    const numberValue = Number(value);
    return Number.isFinite(numberValue)
        ? Math.min(maximum, Math.max(minimum, numberValue))
        : fallback;
}
