import {load} from "js-yaml";
import {beforeAll, describe, expect, it} from "vitest";

import {coreLib, initializeLibrary, uint8ArrayToWasm} from "../integrations/wasm";
import type {FeatureSearchStyleRule} from "../shared/feature-search-state";
import {
    canonicalLayerAffinityExpression,
    canonicalSearchStyleFilename,
    convertSearchStyleRulesToYaml,
    decodeCanonicalLayerAffinity,
    projectStyleSourceForSearch,
    projectStyleSourceToQuick,
    updateStyleSourceFromQuick,
    updateStyleSourceMetadata
} from "./search-style-sheet.converter";

describe("search style sheet codec", () => {
    beforeAll(async () => {
        await initializeLibrary();
    });

    const rules: FeatureSearchStyleRule[] = [
        {
            name: "UI-only name",
            autoGenerated: true,
            geometry: "line",
            filter: [{field: "speed", op: ">=", value: 80}],
            color: {mode: "solid", color: "#ff0000"},
            width: 7,
            opacity: 0.8
        },
        {
            geometry: "point",
            filter: [],
            color: {mode: "solid", color: "#00ff00"},
            pointRadius: 8
        },
        {
            geometry: "label",
            filter: [],
            color: {mode: "solid", color: "#ffffff"},
            opacity: 0.5,
            width: 22,
            labelExpression: "typeId",
            labelBackgroundColor: "#000000"
        }
    ];

    const saveOptions = (
        name: string,
        defaultEnabled = false,
        layerIds: readonly string[] = []
    ) => ({name, defaultEnabled, layerIds});

    it("emits deterministic exact-name category-search YAML with flat rules", () => {
        const first = convertSearchStyleRulesToYaml(saveOptions("Team/Road emphasis"), rules);
        const second = convertSearchStyleRulesToYaml(saveOptions("Team/Road emphasis"), rules);
        const parsed = load(first.source) as any;

        expect(first).toEqual(second);
        expect(parsed.name).toBe("Team/Road emphasis");
        expect(parsed.category).toBe("search");
        expect(parsed.default).toBe(false);
        expect(parsed.version).toBe(2);
        expect(parsed.rules).toHaveLength(3);
        expect(parsed.rules[0]).not.toHaveProperty("all-of");
        expect(parsed.rules[0]).not.toHaveProperty("scope");
        expect(parsed.rules[0].geometry).toEqual(["line"]);
        expect(parsed.rules[0].filter).toBe("speed >= 80");
        expect(parsed.rules[1].width).toBe(8);
        expect(parsed.rules[2]["label-background-color"]).toBe("#000000");
        expect(first.source).not.toContain("UI-only name");
        expect(first.source).not.toContain("autoGenerated");
        expect(first.filename).toBe("Team-Road-emphasis.yaml");
    });

    it("produces a category-search sheet accepted by the native parser", () => {
        const generated = convertSearchStyleRulesToYaml(saveOptions("Team/Road emphasis"), rules);
        const style = uint8ArrayToWasm(
            wasmBuffer => new coreLib.FeatureLayerStyle(wasmBuffer),
            new TextEncoder().encode(generated.source)
        );

        expect(style.isValid(), JSON.stringify(style.validationReport())).toBe(true);
        expect(style.defaultEnabled()).toBe(false);
        expect(style.category()).toBe(coreLib.StyleCategory.Search);
        style.delete();
    });

    it("round-trips canonical YAML through the detached search projection without filter drift", () => {
        const generated = convertSearchStyleRulesToYaml(saveOptions("Round trip"), rules);
        const projected = projectStyleSourceForSearch(generated.source, "feature");
        const regenerated = convertSearchStyleRulesToYaml(saveOptions("Round trip copy"), projected.rules);
        const first = load(generated.source) as any;
        const second = load(regenerated.source) as any;

        expect(projected.omissions).toEqual([]);
        expect(second.rules).toEqual(first.rules);
    });

    it("rejects empty rules and values conversion cannot preserve", () => {
        expect(() => convertSearchStyleRulesToYaml(saveOptions("Empty"), [])).toThrow(/at least one/i);
        expect(() => convertSearchStyleRulesToYaml(saveOptions("Broken"), [{
            geometry: "line",
            filter: [{field: "speed", op: "approximately", value: 80}],
            color: {
                mode: "categories",
                field: "kind",
                stops: [{value: {nested: true}, color: "#ffffff"}]
            }
        }])).toThrow(/unsupported operator.*non-scalar value/i);
    });

    it("emits the chosen default and exact deterministic layer affinity", () => {
        const generated = convertSearchStyleRulesToYaml(
            saveOptions("Scoped", true, ["roads.v2", "lane[0]", "roads.v2"]),
            rules);
        const parsed = load(generated.source) as any;
        const style = uint8ArrayToWasm(
            wasmBuffer => new coreLib.FeatureLayerStyle(wasmBuffer),
            new TextEncoder().encode(generated.source)
        );

        expect(parsed.default).toBe(true);
        expect(parsed.layer).toBe("^(lane\\[0\\]|roads\\.v2)$");
        expect(style.defaultEnabled()).toBe(true);
        expect(style.hasLayerAffinity("lane[0]")).toBe(true);
        expect(style.hasLayerAffinity("roads.v2")).toBe(true);
        expect(style.hasLayerAffinity("roadsXv2")).toBe(false);
        style.delete();
    });

    it("omits affinity for Any and preserves exact whitespace-bearing IDs", () => {
        const any = load(convertSearchStyleRulesToYaml(
            saveOptions("Any", false, []), rules).source) as any;
        const exact = convertSearchStyleRulesToYaml(
            saveOptions("Whitespace", false, [" roads "]), rules);
        const style = uint8ArrayToWasm(
            wasmBuffer => new coreLib.FeatureLayerStyle(wasmBuffer),
            new TextEncoder().encode(exact.source)
        );

        expect(any).not.toHaveProperty("layer");
        expect(style.hasLayerAffinity(" roads ")).toBe(true);
        expect(style.hasLayerAffinity("roads")).toBe(false);
        style.delete();
    });

    it("projects and losslessly updates Quick name and layer affinity metadata", () => {
        const exactIds = [" roads ", "lane[0]", "pipe|slash\\value"];
        const exactExpression = canonicalLayerAffinityExpression(exactIds);
        const source = `# retained root comment
name: Original
layer: ${JSON.stringify(exactExpression)}
custom-root: retained
rules:
  - geometry: [line] # retained rule comment
    color: "#ff0000"
`;
        const projection = projectStyleSourceToQuick(source);

        expect(projection.name).toBe("Original");
        expect(projection.layerAffinity).toEqual({
            kind: "exact",
            layerIds: [...exactIds].sort()
        });
        expect(decodeCanonicalLayerAffinity(exactExpression)).toEqual([...exactIds].sort());
        expect(decodeCanonicalLayerAffinity("Road.*")).toBeUndefined();

        const renamed = updateStyleSourceMetadata(source, {name: "Renamed: Style"});
        const cleared = updateStyleSourceMetadata(renamed, {layerAffinity: {kind: "any"}});
        const parsed = load(cleared) as any;
        expect(cleared).toContain("# retained root comment");
        expect(cleared).toContain("# retained rule comment");
        expect(parsed.name).toBe("Renamed: Style");
        expect(parsed).not.toHaveProperty("layer");
        expect(parsed["custom-root"]).toBe("retained");

        const custom = projectStyleSourceToQuick(source.replace(
            JSON.stringify(exactExpression),
            JSON.stringify("Road.*")));
        expect(custom.layerAffinity).toEqual({kind: "custom", expression: "Road.*"});
    });

    it("applies only effective compatible rules and reports every omission", () => {
        const source = `
name: Mixed/Search
category: search
version: 2
rules:
  - scope: feature
    geometry: line
    color: "#ff0000"
  - scope: attribute
    geometry: point
    color: "#00ff00"
  - geometry: line
    first-of:
      - color: "#0000ff"
`;
        const feature = projectStyleSourceForSearch(source, "feature");

        expect(feature.rules).toHaveLength(1);
        expect(feature.totalRuleCount).toBe(3);
        expect(feature.omissions.map(item => item.code)).toEqual([
            "scope-incompatible",
            "quick-read-only"
        ]);
    });

    it("patches supported fields while preserving comments, root data, and unsupported keys", () => {
        const source = `# retained root comment
name: Base
version: 2
custom-root: retained
rules:
  - geometry: [line] # retained rule comment
    color: "#ff0000"
    width: 3
    glow: {color: "#ffffff", radius: 2}
  - geometry: [point]
    first-of:
      - color: "#00ff00"
`;
        const projection = projectStyleSourceToQuick(source);
        const first = structuredClone(projection.editableRules[0].rule);
        first.width = 9;
        const updated = updateStyleSourceFromQuick(source, projection, [{sourceIndex: 0, rule: first}]);
        const parsed = load(updated) as any;

        expect(updated).toContain("# retained root comment");
        expect(updated).toContain("# retained rule comment");
        expect(parsed["custom-root"]).toBe("retained");
        expect(parsed.rules[0].width).toBe(9);
        expect(parsed.rules[0].glow).toEqual({color: "#ffffff", radius: 2});
        expect(parsed.rules[1]["first-of"]).toHaveLength(1);
        expect(projection.category).toBe("base");
        expect(projection.readOnlyRuleIndices).toEqual([1]);
        expect(projection.warnings.map(warning => warning.code)).toContain("unsupported-property");
        expect(projection.warnings.every(warning => Number.isInteger(warning.sourceIndex))).toBe(true);
        expect(projection.warnings.find(warning => warning.code === "unsupported-property")?.sourceIndex)
            .toBe(0);
        expect(projection.warnings.find(warning => warning.code === "branch-rule")?.sourceIndex)
            .toBe(1);
    });

    it("encodes unsafe stylesheet names only in the download filename", () => {
        expect(canonicalSearchStyleFilename("Folder/A:B * style")).toBe("Folder-A-B-style.yaml");
        expect(canonicalSearchStyleFilename("CON")).toBe("_CON.yaml");
        expect(canonicalSearchStyleFilename("道路")).toBe("search-style.yaml");
    });
});
