import {z} from "zod";
import {boundedUnicodeString} from "../shared/unicode-string.js";
import {appStateTargetSchemas, colorSchema, identifierSchema, indexSchema, styleOptionValueSchema} from "../shared/app-state-channel.contract.js";

const text = boundedUnicodeString(4096);
const count = z.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER);
const tileId = z.number().int().min(-2147483648).max(2147483647);
const limit = z.number().int().min(1).max(100).optional();
const observed = {observedAt: z.string()};
const bounded = {complete: z.boolean(), reason: z.enum(["item_limit", "byte_limit", "text_limit", "loading"]).optional()};
const view = {viewIndex: indexSchema, viewLayoutRevision: indexSchema};
const applied = z.strictObject({status: z.literal("applied"), changed: z.boolean(), viewLayoutRevision: indexSchema});
const sourceText = boundedUnicodeString(48000, true);
/** Leaves room for metadata and the relay envelope within the existing 256 KiB result budget. */
export const VIEWER_SCREENSHOT_MAX_BASE64 = 240000;
const inspectionTargetFields = {
    attributeIndex: count.optional().describe("Observed attribute index on the base feature; mutually exclusive with relationIndex and an ID suffix."),
    relationIndex: count.optional().describe("Observed relation index on the base feature; mutually exclusive with attributeIndex and an ID suffix."),
    validityIndex: count.optional().describe("Observed validity index; requires attributeIndex or relationIndex. For a relation, addresses targetValidity, not sourceValidity. Omit to select the whole attribute/relation.")
};
export const featureIdentitySchema = z.union([
    z.strictObject({...inspectionTargetFields, mapTileKey: identifierSchema, featureId: identifierSchema.describe("Full feature ID, including its feature-type prefix; copy an observed ID, not only its numeric parts.")}),
    z.strictObject({...inspectionTargetFields, mapId: identifierSchema, layerId: identifierSchema.optional(), featureId: identifierSchema.describe("Full feature ID beginning with its exact feature type, with source-specific ID parts separated by dots.")})
]);
const resolvedFeatureSchema = z.strictObject({mapTileKey: identifierSchema, featureId: identifierSchema});
const boundsSchema = z.strictObject({west: z.number().min(-180).max(180), south: z.number().min(-85.05113).max(85.05113),
    east: z.number().min(-180).max(180), north: z.number().min(-85.05113).max(85.05113)});
const mapLayerSchema = z.strictObject({mapId: identifierSchema, layerId: identifierSchema});
const colorStopSchema = z.strictObject({color: colorSchema, value: z.union([text, z.number(), z.boolean(), z.null()])});
export const searchStyleRuleSchema = z.strictObject({
    name: text.optional(), autoGenerated: z.boolean().optional(),
    geometry: z.array(z.enum(["any", "point", "line", "surface", "polygon", "mesh", "label"])).min(1).max(7),
    filter: z.array(z.strictObject({field: text, op: z.enum(["=", "==", "!=", "<", "<=", ">", ">=", "contains"]), value: z.union([text, z.number(), z.boolean(), z.null()]).optional(), customExpression: z.boolean().optional()})).max(25),
    color: z.union([
        z.strictObject({mode: z.literal("solid"), color: colorSchema}),
        z.strictObject({mode: z.enum(["gradient", "categories"]), field: text, customField: z.boolean().optional(),
            stops: z.array(colorStopSchema).max(512), fallbackColor: colorSchema.optional()})
    ]),
    width: z.number().min(0).max(1000).optional(), pointRadius: z.number().min(0).max(1000).optional(),
    opacity: z.number().min(0).max(1).optional(), labelExpression: text.optional(), labelCustomExpression: z.boolean().optional(),
    labelBackgroundColor: colorSchema.optional()
});
export const searchSettingsSchema = z.strictObject({
    scope: z.enum(["auto", "feature", "attribute"]), autoUpdate: z.boolean(), bookmarked: z.boolean(),
    enabled: z.boolean(), showResultsOnMap: z.boolean(), pinColor: colorSchema,
    selectedMapLayers: z.array(mapLayerSchema).max(100), selectedFeatureTypes: z.array(identifierSchema).max(100),
    selectedTileLevels: z.array(z.number().int().min(0).max(15)).max(16), selectedViewIndices: z.array(indexSchema).min(1).max(2),
    searchStyleRules: z.array(searchStyleRuleSchema).max(50),
    renderStrategy: z.strictObject({showLowFiDots: z.boolean(), showBucketLabels: z.boolean(), showHighFiGeometry: z.boolean(),
        showHighFiResultDots: z.boolean(), highFidelityMaxVisibleTiles: z.number().int().min(1).max(65536),
        densityHeatGradient: z.boolean(), densitySizeMultiplier: z.number().min(0.5).max(3)})
});
const searchStatusSchema = z.strictObject({searchId: identifierSchema, query: text, runId: z.string(), refresh: count,
    complete: z.boolean(), paused: z.boolean(), resultCount: count, progressDone: count, progressTotal: count,
    errors: z.array(text).max(100)});
const resultSchema = z.strictObject({
    label: text, mapId: identifierSchema, layerId: identifierSchema, featureId: identifierSchema,
    resultIndex: count, resultKey: identifierSchema, mapTileKey: identifierSchema, sourceTileKey: identifierSchema,
    sourceMapId: identifierSchema, sourceLayerId: identifierSchema, sourceTileId: tileId, hoverFeatureId: identifierSchema,
    attributeIndex: count.optional(), validityIndex: count.optional(), validityCount: count.optional()
});
const resultsInput = {searchId: identifierSchema, offset: count.optional(), limit, runId: identifierSchema.optional(), refresh: count.optional()};
const resultsOutput = {searchId: identifierSchema, runId: z.string(), refresh: count, offset: count, total: count,
    searchComplete: z.boolean(), results: z.array(resultSchema).max(100), ...bounded};
const issueSchema = z.strictObject({severity: z.enum(["info", "warning", "error"]), message: text, phase: text,
    rulePath: text.optional(), property: text.optional(), line: count.optional(), column: count.optional()});
const styleReportSchema = z.strictObject({valid: z.boolean(), loadable: z.boolean(), runtimeVerified: z.literal(false), guidance: text, issues: z.array(issueSchema).max(100), ...bounded});

/** Semantic operations are independent of DOM controls and reuse the ordinary application owners. */
export const viewerOperations = {
    viewer_get_catalog: {
        description: "List one catalog: kind=styles finds editable stylesheet IDs; kind=options finds a layer’s style toggles; kind=layers finds renderable map layers; kind=maps, backgrounds or presets finds those resources. Choose kind explicitly; a layer list is not a list of styles or capabilities. layerType=SourceData or all explicitly includes raw tables. Use mapId to focus on the current map. Layer items include tile levels and schemaFeatureTypes (types with schemas in this layer); featureTypes may additionally contain reference-only identifiers and does not prove feature presence. Options include writeTarget: pass it as target with value and this response’s viewLayoutRevision to viewer_set_app_state. Follow nextOffset with the same filters for another page. No feature/schema loading; omits URLs and credentials.",
        permission: "viewer-read", mutation: false,
        inputSchema: z.strictObject({kind: z.enum(["maps", "layers", "backgrounds", "styles", "options", "presets"]).describe("Required catalog selector. Use styles to find a stylesheet, options for styling controls (requires mapId and layerId), layers for data layers."), viewIndex: indexSchema.optional(),
            mapId: identifierSchema.optional(), layerId: identifierSchema.optional(), styleId: identifierSchema.optional(), layerType: z.enum(["Features", "SourceData", "all"]).default("Features"), offset: count.max(100000).optional(), limit}),
        outputSchema: z.strictObject({...observed, ...bounded, viewLayoutRevision: indexSchema, kind: z.enum(["maps", "layers", "backgrounds", "styles", "options", "presets"]),
            relatedCatalogs: z.array(z.strictObject({purpose: text, arguments: z.strictObject({
                kind: z.enum(["layers", "styles", "options", "presets"]), mapId: identifierSchema.optional(),
                layerId: identifierSchema.optional(), layerType: z.enum(["Features", "SourceData", "all"]).optional()
            })})).max(3), nextOffset: count.optional(), items: z.array(z.strictObject({
            id: identifierSchema, name: text, kind: text, mapId: identifierSchema.optional(), layerId: identifierSchema.optional(),
            styleId: identifierSchema.optional(), value: styleOptionValueSchema.optional(), defaultValue: styleOptionValueSchema.optional(),
            description: text.optional(), visible: z.boolean().optional(), available: z.boolean().optional(),
            imported: z.boolean().optional(), modified: z.boolean().optional(),
            zoomLevels: z.array(z.number().int().min(0).max(15)).max(16).optional(),
            featureTypes: z.array(identifierSchema).max(1000).optional(), schemaFeatureTypes: z.array(identifierSchema).max(1000).optional(), partitionKind: z.enum(["tile", "object"]).optional(),
            writeTarget: appStateTargetSchemas["view.styleOption"].optional()
        })).max(100)})
    },
    viewer_manage_view: {
        description: "Create a second comparison view or remove an existing view. For create, viewIndex identifies the EXISTING source view (normally 0), not the new view; at most two views are supported. Read app.views afterward for indices and the new viewLayoutRevision. For remove, viewIndex identifies the view to remove. Cannot remove the last view.",
        permission: "viewer-control", mutation: true,
        inputSchema: z.strictObject({operation: z.enum(["create", "remove"]), ...view}), outputSchema: applied
    },
    viewer_navigate: {
        description: "Locate and fit feature(s), a tile, or WGS84 bounds in an explicit view. Set the intended projection and panel layout first; refit after changing them. Honors synchronization; human movement during loading cancels the later camera commit. Applied is not render completion.",
        permission: "viewer-control", mutation: true,
        inputSchema: z.strictObject({...view, target: z.union([
            z.strictObject({features: z.array(featureIdentitySchema).min(1).max(50)}),
            z.strictObject({mapTileKey: identifierSchema}), z.strictObject({bounds: boundsSchema})
        ])}), outputSchema: applied
    },
    viewer_inspect: {
        description: "Open feature/entity inspections in the ordinary UI. For an attribute validity, copy the base featureId plus attributeIndex and validityIndex from native extraction or search results. relationIndex similarly addresses a relation. Existing suffixed IDs remain supported; do not combine a suffix with numeric selectors. Returns panel IDs immediately; loading remains observable via app.selections. panelId must address an unlocked feature panel; newPanel opens one grouped panel. To distinguish groups (e.g. predecessors versus successors), call separately with newPanel:true and different color values. color requires newPanel:true and colors only that new panel. lock=true pins the resulting panels. Use mapget extraction for model content.",
        permission: "viewer-control", mutation: true,
        inputSchema: z.strictObject({features: z.array(featureIdentitySchema).min(1).max(50), lock: z.boolean().optional(),
            panelId: indexSchema.optional(), newPanel: z.boolean().optional(), color: colorSchema.optional()}),
        outputSchema: z.strictObject({status: z.literal("applied"), panelIds: z.array(indexSchema).max(50),
            features: z.array(resolvedFeatureSchema).max(50), ...bounded})
    },
    viewer_close_inspection: {
        description: "Remove one inspection, including locked panels. This also removes its feature selection, highlight and displayed ID. It is not a way to hide settings dialogs. For a screenshot requiring the selected feature or its ID, retain that inspection and close only the obstructing settings UI. Other inspections are preserved.",
        permission: "viewer-control", mutation: true,
        inputSchema: z.strictObject({panelId: indexSchema}), outputSchema: applied
    },
    viewer_open_source_data: {
        description: "Open a source-data inspection at a lossless uint64 address. Use a native SourceData mapTileKey, or map/partition and a mapget-native source reference returned by extraction. The existing panel owns loading and reveals the reference.",
        permission: "viewer-control", mutation: true,
        inputSchema: z.strictObject({source: z.union([
            z.strictObject({mapTileKey: identifierSchema, address: z.string().regex(/^[0-9]+$/).max(20).optional()}),
            z.strictObject({mapId: identifierSchema, partition: z.union([
                z.strictObject({kind: z.literal("tile"), id: tileId}),
                z.strictObject({kind: z.literal("object"), id: z.string().regex(/^(0|[1-9][0-9]*)$/).max(20)})
            ]), reference: z.strictObject({layerId: identifierSchema, address: z.string().regex(/^[0-9]+$/).max(20), qualifier: text.optional()})})
        ]), newPanel: z.boolean().optional()}),
        outputSchema: z.strictObject({status: z.literal("applied"), panelId: indexSchema, mapTileKey: identifierSchema})
    },
    viewer_start_search: {
        description: "Start an ordinary visible simfil search with explicit layers/views and bounded viewport coverage. Auto-update defaults to false. Returns searchId. For ad-hoc labels, highlighting or colors from actual data fields, configure searchStyleRules with viewer_set_search; stock style toggles are not required. Cancelling this completed call does not stop the search. Use viewer_control_search for lifecycle control.",
        permission: "viewer-control", mutation: true,
        inputSchema: z.strictObject({query: boundedUnicodeString(4096, true), scope: z.enum(["auto", "feature", "attribute"]).optional(),
            mapLayers: z.array(mapLayerSchema).min(1).max(100), viewIndices: z.array(indexSchema).min(1).max(2),
            tileLevels: z.array(z.number().int().min(0).max(15)).max(16).optional(), autoUpdate: z.boolean().optional(), viewLayoutRevision: indexSchema}),
        outputSchema: z.strictObject({status: z.literal("applied"), searchId: identifierSchema})
    },
    viewer_control_search: {
        description: "Pause/resume/stop/close/rerun/refresh an existing search. Stop retains partial results; close removes its saved definition. Rerun requires query; refresh explicitly updates viewport coverage.",
        permission: "viewer-control", mutation: true,
        inputSchema: z.strictObject({searchId: identifierSchema, operation: z.enum(["pause", "resume", "stop", "close", "rerun", "refresh"]), query: boundedUnicodeString(4096, true).optional()}),
        outputSchema: applied
    },
    viewer_get_search: {
        description: "Read one search's settings, progress and schemaAnalysis (resolved scope, normalized query and rewrite diagnostics). resultCount counts matching contexts: features in feature scope, attribute/validity contexts in attribute scope. One assignment may have several matching validities. While schemaAnalysis.status=pending, no final result count is available. searchComplete=false means resultCount is provisional, even if responseComplete=true. Starting an asynchronous search is enough for an honestly reported applied visualization; claim final counts or no matches only when searchComplete=true and status.errors is empty.",
        permission: "viewer-read", mutation: false,
        inputSchema: z.strictObject({searchId: identifierSchema}),
        outputSchema: z.strictObject({...observed, responseComplete: z.boolean(), searchComplete: z.boolean(),
            reason: bounded.reason, settings: searchSettingsSchema, status: searchStatusSchema,
            schemaAnalysis: z.strictObject({status: z.enum(["pending", "ready", "error"]),
                concreteScope: z.enum(["feature", "attribute"]), normalizedQuery: boundedUnicodeString(4096),
                rewriteSuppressed: z.boolean(), rewriteSuppressionReason: boundedUnicodeString(1024),
                error: boundedUnicodeString(4096).optional()})})
    },
    viewer_set_search: {
        description: "Patch one search's settings: provide only changed fields; omitted fields stay unchanged. renderStrategy also merges by field; arrays such as searchStyleRules replace the whole array. To draw matching geometry instead of bubbles: keep showResultsOnMap=true, set renderStrategy.showHighFiGeometry=true, disable unwanted showHighFiResultDots/showLowFiDots/showBucketLabels, and choose a highFidelityMaxVisibleTiles threshold appropriate to the view. Hiding results does not draw matching geometry. autoUpdate=false freezes existing results. May rerun the query; retains searchId.",
        permission: "viewer-control", mutation: true,
        inputSchema: z.strictObject({searchId: identifierSchema, settings: searchSettingsSchema.partial().extend({renderStrategy: searchSettingsSchema.shape.renderStrategy.partial().optional()}), viewLayoutRevision: indexSchema}), outputSchema: applied
    },
    viewer_get_search_results: {
        description: "Read a bounded slice of an existing search's result identities. Attribute results include attributeIndex and validityIndex; multiple rows can belong to one assignment or feature. Optional runId/refresh guards reject stale slices. No new query or full-feature traversal.",
        permission: "viewer-read", mutation: false,
        inputSchema: z.strictObject(resultsInput), outputSchema: z.strictObject({...observed, ...resultsOutput})
    },
    viewer_export_search: {
        description: "Return bounded JSON search configuration/results as text, without browser download or clipboard access. Exported partial results are explicitly marked; use runId/refresh to guard slices.",
        permission: "viewer-read", mutation: false,
        inputSchema: z.strictObject({...resultsInput, include: z.enum(["configuration", "results", "both"])}),
        outputSchema: z.strictObject({...observed, ...bounded, mimeType: z.literal("application/json"), content: boundedUnicodeString(180000)})
    },
    viewer_get_share_link: {
        description: "Return a link for the current URL-backed cameras, layers, style options and selections using the viewer's normal URL codec. Does not copy unknown/authentication URL parameters, modify the tab, publish anything or contact another person. Browser-local search overlays and YAML styles are not embedded; localSearchIds and localStyleIds identify dependencies the recipient would also need. Export searches separately with viewer_export_search and styles with viewer_get_style. localOnly means the hostname is loopback: recipients need an accessible address for the same configured viewer.",
        permission: "viewer-read", mutation: false,
        inputSchema: z.strictObject({}),
        outputSchema: z.strictObject({...observed, ...bounded, url: boundedUnicodeString(48000, true),
            localOnly: z.boolean(), localStyleIds: z.array(identifierSchema).max(100), localSearchIds: z.array(identifierSchema).max(100)})
    },
    viewer_get_style: {
        description: "Read one style's YAML and browser-local lifecycle flags. A style shows how some fields are drawn; it is not a data inventory. Discover available attributes with mapget_query_schema and actual values with mapget_extract_features. Search-overlay colors, categories and labels belong to viewer_get_search/viewer_set_search, not this base stylesheet. Never returns credentials or source filesystem paths.",
        permission: "viewer-read", mutation: false,
        inputSchema: z.strictObject({styleId: identifierSchema.describe("Copy the exact id from viewer_get_catalog kind:styles; do not use the layer ID or display name.")}),
        outputSchema: z.strictObject({styleId: identifierSchema, source: boundedUnicodeString(180000), imported: z.boolean(), modified: z.boolean(), visible: z.boolean()})
    },
    viewer_validate_style: {
        description: "Validate bounded style YAML structure using the native parser without installing it. valid/loadable do not prove fields, geometry or rendered output exist in a dataset. After applying, use viewer_get_diagnostics sections=[errors] for runtime expression failures. Options are local to each stylesheet: copied option filters require matching options declarations in that stylesheet.",
        permission: "viewer-read", mutation: false,
        inputSchema: z.strictObject({source: sourceText}), outputSchema: styleReportSchema
    },
    viewer_edit_style: {
        description: "Create/update/patch/reset a browser-local YAML style, delete an imported style, or change visibility. Prefer patch for focused changes after viewer_get_style: edits are sequential exact find/replace pairs, each find must occur exactly once in the current source. All edits and final YAML validation succeed before any change is installed. Preserve unrelated rules/options. Missing stock options do not prevent custom rules. Options belong to each stylesheet; declare copied option filters locally. Never writes server files. Create/update require source; patch requires styleId and edits. Reset restores builtin YAML, not visibility or option values.",
        permission: "viewer-control", mutation: true,
        inputSchema: z.strictObject({operation: z.enum(["create", "update", "patch", "reset", "delete", "visibility"]), styleId: identifierSchema.optional(),
            source: sourceText.optional(), visible: z.boolean().optional(),
            edits: z.array(z.strictObject({find: boundedUnicodeString(16000, true), replace: boundedUnicodeString(32000)})).min(1).max(16).optional()}),
        outputSchema: z.strictObject({status: z.literal("applied"), styleId: identifierSchema, changed: z.boolean().optional(), editCount: indexSchema.optional()})
    },
    viewer_screenshot: {
        description: "Capture the visible application viewport, including maps, labels, highlights, panels and overlays, but not browser chrome. The JPEG is already attached as image content in this tool result; refer to the captured image in prose and continue the requested report. Never transcribe image bytes, emit a base64/data URI, or invent a download/attachment URL. DOM-based capture is approximate and is not a render-ready fence. No clipboard or file download. maxWidth/maxHeight bound the whole image without cropping; defaults 1280x960. Requires viewer-read and an explicit tab.",
        permission: "viewer-read", mutation: false,
        inputSchema: z.strictObject({maxWidth: z.number().int().min(128).max(1920).optional(),
            maxHeight: z.number().int().min(128).max(1920).optional(), viewLayoutRevision: indexSchema.optional()}),
        // Native MCP promotes image to ImageContent and advertises/returns only this self-contained metadata schema as structuredContent.
        outputSchema: z.strictObject({
            image: z.strictObject({mimeType: z.literal("image/jpeg"), data: z.string().min(4).max(VIEWER_SCREENSHOT_MAX_BASE64)}),
            metadata: z.strictObject({scope: z.literal("application-viewport"),
                width: z.number().int().min(1).max(1920), height: z.number().int().min(1).max(1920),
                viewportWidth: z.number().int().min(1).max(32768), viewportHeight: z.number().int().min(1).max(32768),
                viewLayoutRevision: indexSchema, capturedAt: z.string(), readiness: z.strictObject({status: z.literal("unknown")}),
                warnings: z.array(text).max(10)
            })
        })
    },
    viewer_get_diagnostics: {
        description: "Read BROWSER transport, render-worker queues, frame-time metrics, cached loading, GPU allocation and style/search errors without resetting the view. Native BACKEND workers/cache/memory require the separately privileged mapget_get_diagnostics tool. Call it only when it appears in your tool catalog; otherwise explain the permission limit. Browser workers and observed transport latency are not backend queue statistics. No scene/tile scan or GPU readback. Cached and unavailable metrics are explicit.",
        permission: "viewer-read", mutation: false,
        inputSchema: z.strictObject({viewIndex: indexSchema.optional(), mapId: identifierSchema.optional(), layerId: identifierSchema.optional(),
            sections: z.array(z.enum(["transport", "workers", "loading", "gpu", "errors"])).max(5).optional(), limit}),
        outputSchema: z.strictObject({...observed, ...bounded,
            executionContext: z.literal("browser"),
            interpretation: text,
            metrics: z.array(z.strictObject({section: text, name: text, value: z.union([z.number(), z.boolean(), z.null()]),
                scope: z.enum(["tab", "view"]), viewIndex: indexSchema.optional(), cached: z.boolean().optional()})).max(100),
            errors: z.array(z.strictObject({source: text, message: text,
                severity: z.enum(["warning", "error"]).optional(), phase: text.optional(),
                property: text.optional(), expression: text.optional(), rulePath: text.optional(),
                mapId: identifierSchema.optional(), layerId: identifierSchema.optional(),
                featureId: identifierSchema.optional()})).max(100), unavailable: z.array(text).max(20)
        })
    }
} as const;
