import {z} from "zod";
import {boundedUnicodeString} from "../shared/unicode-string.js";
import {colorSchema, identifierSchema, indexSchema, styleOptionValueSchema} from "../shared/app-state-channel.contract.js";

const text = boundedUnicodeString(4096);
const count = z.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER);
const tileId = z.number().int().min(-2147483648).max(2147483647);
const limit = z.number().int().min(1).max(100).optional();
const observed = {observedAt: z.string()};
const bounded = {complete: z.boolean(), reason: z.enum(["item_limit", "byte_limit", "text_limit", "loading"]).optional()};
const view = {viewIndex: indexSchema, viewLayoutRevision: indexSchema};
const applied = z.strictObject({status: z.literal("applied"), changed: z.boolean(), viewLayoutRevision: indexSchema});
const sourceText = boundedUnicodeString(48000, true);
/** Leaves room for metadata and the relay envelope within the existing 256 KiB result budget. */
export const VIEWER_SCREENSHOT_MAX_BASE64 = 240000;
export const featureIdentitySchema = z.union([
    z.strictObject({mapTileKey: identifierSchema, featureId: identifierSchema}),
    z.strictObject({mapId: identifierSchema, layerId: identifierSchema.optional(), featureId: identifierSchema})
]);
const resolvedFeatureSchema = z.strictObject({mapTileKey: identifierSchema, featureId: identifierSchema});
const boundsSchema = z.strictObject({west: z.number().min(-180).max(180), south: z.number().min(-85.05113).max(85.05113),
    east: z.number().min(-180).max(180), north: z.number().min(-85.05113).max(85.05113)});
const mapLayerSchema = z.strictObject({mapId: identifierSchema, layerId: identifierSchema});
const colorStopSchema = z.strictObject({color: colorSchema, value: z.union([text, z.number(), z.boolean(), z.null()])});
export const searchStyleRuleSchema = z.strictObject({
    name: text.optional(), autoGenerated: z.boolean().optional(),
    geometry: z.array(z.enum(["any", "point", "line", "surface", "polygon", "mesh", "label"])).min(1).max(7),
    filter: z.array(z.strictObject({field: text, op: text, value: z.union([text, z.number(), z.boolean(), z.null()]).optional(), customExpression: z.boolean().optional()})).max(25),
    color: z.union([
        z.strictObject({mode: z.literal("solid"), color: colorSchema}),
        z.strictObject({mode: z.enum(["gradient", "categories"]), field: text, customField: z.boolean().optional(),
            stops: z.array(colorStopSchema).max(512), fallbackColor: colorSchema.optional()})
    ]),
    width: z.number().min(0).max(1000).optional(), pointRadius: z.number().min(0).max(1000).optional(),
    opacity: z.number().min(0).max(1).optional(), labelExpression: text.optional(), labelCustomExpression: z.boolean().optional(),
    labelBackgroundColor: colorSchema.optional()
});
export const searchSettingsSchema = z.strictObject({
    scope: z.enum(["auto", "feature", "attribute"]), autoUpdate: z.boolean(), bookmarked: z.boolean(),
    enabled: z.boolean(), showResultsOnMap: z.boolean(), pinColor: colorSchema,
    selectedMapLayers: z.array(mapLayerSchema).max(100), selectedFeatureTypes: z.array(identifierSchema).max(100),
    selectedTileLevels: z.array(z.number().int().min(0).max(15)).max(16), selectedViewIndices: z.array(indexSchema).min(1).max(2),
    searchStyleRules: z.array(searchStyleRuleSchema).max(50),
    renderStrategy: z.strictObject({showLowFiDots: z.boolean(), showBucketLabels: z.boolean(), showHighFiGeometry: z.boolean(),
        showHighFiResultDots: z.boolean(), highFidelityMaxVisibleTiles: z.number().int().min(1).max(65536),
        densityHeatGradient: z.boolean(), densitySizeMultiplier: z.number().min(0.5).max(3)})
});
const searchStatusSchema = z.strictObject({searchId: identifierSchema, query: text, runId: z.string(), refresh: count,
    complete: z.boolean(), paused: z.boolean(), resultCount: count, progressDone: count, progressTotal: count,
    errors: z.array(text).max(100)});
const resultSchema = z.strictObject({
    label: text, mapId: identifierSchema, layerId: identifierSchema, featureId: identifierSchema,
    resultIndex: count, resultKey: identifierSchema, mapTileKey: identifierSchema, sourceTileKey: identifierSchema,
    sourceMapId: identifierSchema, sourceLayerId: identifierSchema, sourceTileId: tileId, hoverFeatureId: identifierSchema,
    attributeIndex: count.optional(), validityIndex: count.optional(), validityCount: count.optional()
});
const resultsInput = {searchId: identifierSchema, offset: count.optional(), limit, runId: identifierSchema.optional(), refresh: count.optional()};
const resultsOutput = {searchId: identifierSchema, runId: z.string(), refresh: count, offset: count, total: count,
    searchComplete: z.boolean(), results: z.array(resultSchema).max(100), ...bounded};
const issueSchema = z.strictObject({severity: z.enum(["info", "warning", "error"]), message: text, phase: text,
    rulePath: text.optional(), property: text.optional(), line: count.optional(), column: count.optional()});
const styleReportSchema = z.strictObject({valid: z.boolean(), loadable: z.boolean(), issues: z.array(issueSchema).max(100), ...bounded});

/** Semantic operations are independent of DOM controls and reuse the ordinary application owners. */
export const viewerOperations = {
    viewer_get_catalog: {
        description: "Discover browser-available layers, backgrounds, styles, options and presets. No feature/schema loading; omits URLs and credentials. Narrow by map/layer/style IDs when incomplete.",
        permission: "viewer-read", mutation: false,
        inputSchema: z.strictObject({kind: z.enum(["layers", "backgrounds", "styles", "options", "presets"]), viewIndex: indexSchema.optional(),
            mapId: identifierSchema.optional(), layerId: identifierSchema.optional(), styleId: identifierSchema.optional(), limit}),
        outputSchema: z.strictObject({...observed, ...bounded, items: z.array(z.strictObject({
            id: identifierSchema, name: text, kind: text, mapId: identifierSchema.optional(), layerId: identifierSchema.optional(),
            styleId: identifierSchema.optional(), value: styleOptionValueSchema.optional(), defaultValue: styleOptionValueSchema.optional(),
            description: text.optional(), visible: z.boolean().optional(), available: z.boolean().optional(),
            imported: z.boolean().optional(), modified: z.boolean().optional()
        })).max(100)})
    },
    viewer_manage_view: {
        description: "Create a comparison view or remove an explicit view through normal layout ownership. Cannot remove the last view.",
        permission: "viewer-control", mutation: true,
        inputSchema: z.strictObject({operation: z.enum(["create", "remove"]), ...view}), outputSchema: applied
    },
    viewer_navigate: {
        description: "Locate and fit feature(s), a tile, or WGS84 bounds in an explicit view. Honors synchronization; human movement during loading cancels the later camera commit. Applied is not render completion.",
        permission: "viewer-control", mutation: true,
        inputSchema: z.strictObject({...view, target: z.union([
            z.strictObject({features: z.array(featureIdentitySchema).min(1).max(50)}),
            z.strictObject({mapTileKey: identifierSchema}), z.strictObject({bounds: boundsSchema})
        ])}), outputSchema: applied
    },
    viewer_inspect: {
        description: "Open feature/entity inspections in the ordinary UI. Feature IDs may include attribute/relation/validity suffixes. Returns panel IDs immediately; loading remains observable via app.selections. panelId must address an unlocked feature panel; newPanel opens a grouped panel. lock=true pins the resulting panels. Use mapget extraction for model content.",
        permission: "viewer-control", mutation: true,
        inputSchema: z.strictObject({features: z.array(featureIdentitySchema).min(1).max(50), lock: z.boolean().optional(),
            panelId: indexSchema.optional(), newPanel: z.boolean().optional()}),
        outputSchema: z.strictObject({status: z.literal("applied"), panelIds: z.array(indexSchema).max(50),
            features: z.array(resolvedFeatureSchema).max(50), ...bounded})
    },
    viewer_close_inspection: {
        description: "Close one explicit inspection, including locked panels. Does not close other inspections.",
        permission: "viewer-control", mutation: true,
        inputSchema: z.strictObject({panelId: indexSchema}), outputSchema: applied
    },
    viewer_open_source_data: {
        description: "Open a source-data inspection at a lossless uint64 address. Use a native SourceData mapTileKey, or map/partition and a mapget-native source reference returned by extraction. The existing panel owns loading and reveals the reference.",
        permission: "viewer-control", mutation: true,
        inputSchema: z.strictObject({source: z.union([
            z.strictObject({mapTileKey: identifierSchema, address: z.string().regex(/^[0-9]+$/).max(20).optional()}),
            z.strictObject({mapId: identifierSchema, partition: z.union([
                z.strictObject({kind: z.literal("tile"), id: tileId}),
                z.strictObject({kind: z.literal("object"), id: z.string().regex(/^(0|[1-9][0-9]*)$/).max(20)})
            ]), reference: z.strictObject({layerId: identifierSchema, address: z.string().regex(/^[0-9]+$/).max(20), qualifier: text.optional()})})
        ]), newPanel: z.boolean().optional()}),
        outputSchema: z.strictObject({status: z.literal("applied"), panelId: indexSchema, mapTileKey: identifierSchema})
    },
    viewer_start_search: {
        description: "Start an ordinary visible search with explicit layers/views and bounded viewport coverage. Auto-update defaults to false. Returns searchId; cancelling this completed call does not stop the search. Use viewer_control_search for lifecycle control.",
        permission: "viewer-control", mutation: true,
        inputSchema: z.strictObject({query: boundedUnicodeString(4096, true), scope: z.enum(["auto", "feature", "attribute"]).optional(),
            mapLayers: z.array(mapLayerSchema).min(1).max(100), viewIndices: z.array(indexSchema).min(1).max(2),
            tileLevels: z.array(z.number().int().min(0).max(15)).max(16).optional(), autoUpdate: z.boolean().optional(), viewLayoutRevision: indexSchema}),
        outputSchema: z.strictObject({status: z.literal("applied"), searchId: identifierSchema})
    },
    viewer_control_search: {
        description: "Pause/resume/stop/close/rerun/refresh an existing search. Stop retains partial results; close removes its saved definition. Rerun requires query; refresh explicitly updates viewport coverage.",
        permission: "viewer-control", mutation: true,
        inputSchema: z.strictObject({searchId: identifierSchema, operation: z.enum(["pause", "resume", "stop", "close", "rerun", "refresh"]), query: boundedUnicodeString(4096, true).optional()}),
        outputSchema: applied
    },
    viewer_get_search: {
        description: "Read one search's full settings and bounded current status/errors without starting schema analysis or reading results.",
        permission: "viewer-read", mutation: false,
        inputSchema: z.strictObject({searchId: identifierSchema}),
        outputSchema: z.strictObject({...observed, ...bounded, settings: searchSettingsSchema, status: searchStatusSchema})
    },
    viewer_set_search: {
        description: "Replace one search's typed scope/presentation settings through its ordinary owner. May rerun its query. Reads and writes retain the same searchId; no whole search-collection replacement.",
        permission: "viewer-control", mutation: true,
        inputSchema: z.strictObject({searchId: identifierSchema, settings: searchSettingsSchema, viewLayoutRevision: indexSchema}), outputSchema: applied
    },
    viewer_get_search_results: {
        description: "Read a bounded slice of an existing search's result identities. Optional runId/refresh guards reject stale slices. No new query or full-feature traversal.",
        permission: "viewer-read", mutation: false,
        inputSchema: z.strictObject(resultsInput), outputSchema: z.strictObject({...observed, ...resultsOutput})
    },
    viewer_export_search: {
        description: "Return bounded JSON search configuration/results as text, without browser download or clipboard access. Exported partial results are explicitly marked; use runId/refresh to guard slices.",
        permission: "viewer-read", mutation: false,
        inputSchema: z.strictObject({...resultsInput, include: z.enum(["configuration", "results", "both"])}),
        outputSchema: z.strictObject({...observed, ...bounded, mimeType: z.literal("application/json"), content: boundedUnicodeString(180000)})
    },
    viewer_get_style: {
        description: "Read one style's YAML and browser-local lifecycle flags. Never returns credentials or source filesystem paths.",
        permission: "viewer-read", mutation: false,
        inputSchema: z.strictObject({styleId: identifierSchema}),
        outputSchema: z.strictObject({styleId: identifierSchema, source: boundedUnicodeString(180000), imported: z.boolean(), modified: z.boolean(), visible: z.boolean()})
    },
    viewer_validate_style: {
        description: "Validate bounded style YAML using the native style parser; return structured issues without installing the style.",
        permission: "viewer-read", mutation: false,
        inputSchema: z.strictObject({source: sourceText}), outputSchema: styleReportSchema
    },
    viewer_edit_style: {
        description: "Create/update/reset a browser-local style, delete an imported style, or change visibility. Never writes server files. Update/reset/delete address an exact styleId; create/update require source.",
        permission: "viewer-control", mutation: true,
        inputSchema: z.strictObject({operation: z.enum(["create", "update", "reset", "delete", "visibility"]), styleId: identifierSchema.optional(),
            source: sourceText.optional(), visible: z.boolean().optional()}),
        outputSchema: z.strictObject({status: z.literal("applied"), styleId: identifierSchema})
    },
    viewer_screenshot: {
        description: "Capture the visible application viewport, including all maps, labels, highlights, inspection panels and overlays, but not browser chrome. Returns a bounded JPEG image and metadata. DOM-based capture is approximate, not a pixel-exact browser screenshot or a render-ready fence. No clipboard, file download or screen-sharing permission. maxWidth/maxHeight bound the whole image without cropping; defaults 1280x960. Requires viewer-read and an explicit tab.",
        permission: "viewer-read", mutation: false,
        inputSchema: z.strictObject({maxWidth: z.number().int().min(128).max(1920).optional(),
            maxHeight: z.number().int().min(128).max(1920).optional(), viewLayoutRevision: indexSchema.optional()}),
        // Native MCP promotes image to ImageContent and advertises/returns only this self-contained metadata schema as structuredContent.
        outputSchema: z.strictObject({
            image: z.strictObject({mimeType: z.literal("image/jpeg"), data: z.string().min(4).max(VIEWER_SCREENSHOT_MAX_BASE64)}),
            metadata: z.strictObject({scope: z.literal("application-viewport"),
                width: z.number().int().min(1).max(1920), height: z.number().int().min(1).max(1920),
                viewportWidth: z.number().int().min(1).max(32768), viewportHeight: z.number().int().min(1).max(32768),
                viewLayoutRevision: indexSchema, capturedAt: z.string(), readiness: z.strictObject({status: z.literal("unknown")}),
                warnings: z.array(text).max(10)
            })
        })
    },
    viewer_get_diagnostics: {
        description: "Read bounded browser transport, render-worker, cached loading, GPU allocation and style/search error diagnostics. No scene/tile scan, GPU readback, full export or backend request. Cached and unavailable metrics are explicit.",
        permission: "viewer-read", mutation: false,
        inputSchema: z.strictObject({viewIndex: indexSchema.optional(), mapId: identifierSchema.optional(), layerId: identifierSchema.optional(),
            sections: z.array(z.enum(["transport", "workers", "loading", "gpu", "errors"])).max(5).optional(), limit}),
        outputSchema: z.strictObject({...observed, ...bounded,
            metrics: z.array(z.strictObject({section: text, name: text, value: z.union([z.number(), z.boolean(), z.null()]),
                scope: z.enum(["tab", "view"]), viewIndex: indexSchema.optional(), cached: z.boolean().optional()})).max(100),
            errors: z.array(z.strictObject({source: text, message: text})).max(100), unavailable: z.array(text).max(20)
        })
    }
} as const;
