import {z} from "zod";

export type FeatureSearchScope = "attribute" | "feature" | "auto";

export interface FeatureSearchRuleFilter {
    field: string;
    op: string;
    value?: unknown;
}

export interface FeatureSearchColorStop {
    color: string;
    value: unknown;
}

export interface FeatureSearchMapLayerRef {
    mapId: string;
    layerId: string;
}

export type FeatureSearchGeometryKind = "any" | "point" | "line" | "surface" | "polygon" | "mesh" | "label";

export type FeatureSearchColorMode =
    | {mode: "solid"; color: string}
    | {mode: "gradient"; field: string; stops: FeatureSearchColorStop[]; fallbackColor?: string}
    | {mode: "categories"; field: string; stops: FeatureSearchColorStop[]; fallbackColor?: string};

export interface FeatureSearchStyleRule {
    name?: string;
    autoGenerated?: boolean;
    geometry: FeatureSearchGeometryKind;
    filter: FeatureSearchRuleFilter[];
    color: FeatureSearchColorMode;
    width?: number;
    pointRadius?: number;
    opacity?: number;
    labelExpression?: string;
    labelCustomExpression?: boolean;
    labelBackgroundColor?: string;
}

export interface FeatureSearchRenderStrategy {
    showLowFiDots: boolean;
    showBucketLabels: boolean;
    showHighFiGeometry: boolean;
    showHighFiResultDots: boolean;
    highFidelityMaxVisibleTiles: number;
    densityHeatGradient: boolean;
    densitySizeMultiplier: number;
}

export interface FeatureSearchStateEntry {
    id: string;
    query: string;
    scope: FeatureSearchScope;
    autoUpdate: boolean;
    bookmarked: boolean;
    enabled: boolean;
    paused: boolean;
    showResultsOnMap: boolean;
    pinColor: string;
    selectedMapLayers: FeatureSearchMapLayerRef[];
    selectedMapLayersManual?: boolean;
    selectedFeatureTypes: string[];
    selectedTileLevels: number[];
    selectedViewIndices: number[];
    searchStyleRules: FeatureSearchStyleRule[];
    renderStrategy: FeatureSearchRenderStrategy;
}

export type FeatureSearchStatePatch = Partial<Omit<FeatureSearchStateEntry, "id">>;

export const FeatureSearchStateSchema = z.array(z.unknown());

const DEFAULT_PIN_COLOR = "#ea4336";
const VALID_SCOPES = new Set<FeatureSearchScope>(["attribute", "feature", "auto"]);
const MAX_FEATURE_SEARCHES = 50;
const MAX_STYLE_RULES_PER_SEARCH = 50;
const MAX_FILTERS_PER_RULE = 25;
const MAX_COLOR_STOPS_PER_RULE = 512;
const MAX_SELECTED_SEARCH_LAYERS = 500;
const MAX_SELECTED_FEATURE_TYPES = 100;
const MAX_SUPPORTED_FEATURE_SEARCH_VIEWS = 2;
export const MIN_FEATURE_SEARCH_TILE_LEVEL = 0;
export const MAX_FEATURE_SEARCH_TILE_LEVEL = 22;
const VALID_GEOMETRIES = new Set<FeatureSearchGeometryKind>(["any", "point", "line", "surface", "polygon", "mesh", "label"]);
const VALID_COLOR_MODES = new Set(["solid", "gradient", "categories"]);
const MIN_HIGH_FIDELITY_VISIBLE_TILES = 1;
const MAX_HIGH_FIDELITY_VISIBLE_TILES = 64 * 1024;
const MIN_DENSITY_SIZE_MULTIPLIER = 0.5;
const MAX_DENSITY_SIZE_MULTIPLIER = 3;
export const DEFAULT_FEATURE_SEARCH_VIEW_INDICES: number[] = Array.from(
    {length: MAX_SUPPORTED_FEATURE_SEARCH_VIEWS},
    (_, index) => index
);
export const DEFAULT_FEATURE_SEARCH_TILE_LEVELS: number[] = [];
export const DEFAULT_FEATURE_SEARCH_LABEL_BACKGROUND_COLOR = "#111827";

export const DEFAULT_FEATURE_SEARCH_RENDER_STRATEGY: FeatureSearchRenderStrategy = {
    showLowFiDots: true,
    showBucketLabels: true,
    showHighFiGeometry: true,
    showHighFiResultDots: false,
    highFidelityMaxVisibleTiles: 512,
    densityHeatGradient: false,
    densitySizeMultiplier: 1
};

function createFeatureSearchId(): string {
    return `feature_search_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
}

function normalizeHexColor(value: unknown, fallback = DEFAULT_PIN_COLOR): string {
    if (typeof value !== "string") {
        return fallback;
    }
    const trimmed = value.trim();
    const longHex = /^#([0-9a-f]{6})$/i.exec(trimmed);
    if (longHex) {
        return `#${longHex[1].toLowerCase()}`;
    }
    const shortHex = /^#([0-9a-f]{3})$/i.exec(trimmed);
    if (shortHex) {
        const [r, g, b] = shortHex[1].split("");
        return `#${r}${r}${g}${g}${b}${b}`.toLowerCase();
    }
    return fallback;
}

function normalizeBoolean(value: unknown, fallback: boolean): boolean {
    if (typeof value === "boolean") {
        return value;
    }
    if (typeof value === "number") {
        return value === 1 ? true : value === 0 ? false : fallback;
    }
    if (typeof value === "string") {
        const normalized = value.trim().toLowerCase();
        if (normalized === "true" || normalized === "1") {
            return true;
        }
        if (normalized === "false" || normalized === "0") {
            return false;
        }
    }
    return fallback;
}

function normalizeScope(value: unknown): FeatureSearchScope {
    return typeof value === "string" && VALID_SCOPES.has(value as FeatureSearchScope)
        ? value as FeatureSearchScope
        : "auto";
}

function normalizeString(value: unknown): string | undefined {
    return typeof value === "string" && value.trim() ? value.trim() : undefined;
}

function normalizeGeometry(value: unknown): FeatureSearchGeometryKind {
    if (typeof value !== "string") {
        return "any";
    }
    const normalized = value.trim();
    if (VALID_GEOMETRIES.has(normalized as FeatureSearchGeometryKind)) {
        return normalized as FeatureSearchGeometryKind;
    }
    if (normalized === "anyGeom") {
        return "any";
    }
    if (normalized === "text") {
        return "label";
    }
    return "any";
}

function normalizeRuleFilters(value: unknown): FeatureSearchRuleFilter[] {
    if (!Array.isArray(value)) {
        return [];
    }
    return value.slice(0, MAX_FILTERS_PER_RULE).flatMap(item => {
        if (!item || typeof item !== "object" || Array.isArray(item)) {
            return [];
        }
        const raw = item as Record<string, unknown>;
        const field = normalizeString(raw["field"]);
        const op = normalizeString(raw["op"]);
        if (!field || !op) {
            return [];
        }
        return [{
            field,
            op,
            ...("value" in raw ? {value: raw["value"]} : {})
        }];
    });
}

function normalizeColorStops(value: unknown): FeatureSearchColorStop[] {
    if (!Array.isArray(value)) {
        return [];
    }
    return value.slice(0, MAX_COLOR_STOPS_PER_RULE).flatMap(item => {
        if (!item || typeof item !== "object" || Array.isArray(item)) {
            return [];
        }
        const raw = item as Record<string, unknown>;
        const color = normalizeHexColor(raw["color"], "");
        if (!color) {
            return [];
        }
        return [{
            color,
            value: raw["value"]
        }];
    });
}

function normalizeSearchMapLayerRefs(value: unknown): FeatureSearchMapLayerRef[] {
    if (!Array.isArray(value)) {
        return [];
    }
    const seen = new Set<string>();
    const refs: FeatureSearchMapLayerRef[] = [];
    for (const item of value.slice(0, MAX_SELECTED_SEARCH_LAYERS)) {
        if (!item || typeof item !== "object" || Array.isArray(item)) {
            continue;
        }
        const raw = item as Record<string, unknown>;
        const mapId = normalizeString(raw["mapId"]);
        const layerId = normalizeString(raw["layerId"]);
        if (!mapId || !layerId) {
            continue;
        }
        const key = JSON.stringify([mapId, layerId]);
        if (seen.has(key)) {
            continue;
        }
        seen.add(key);
        refs.push({mapId, layerId});
    }
    return refs;
}

function normalizeSearchViewIndices(value: unknown): number[] {
    if (!Array.isArray(value)) {
        return [...DEFAULT_FEATURE_SEARCH_VIEW_INDICES];
    }
    const seen = new Set<number>();
    const indices: number[] = [];
    for (const item of value) {
        const index = Number(item);
        if (!Number.isInteger(index) || index < 0 || index >= MAX_SUPPORTED_FEATURE_SEARCH_VIEWS || seen.has(index)) {
            continue;
        }
        seen.add(index);
        indices.push(index);
    }
    return indices.sort((lhs, rhs) => lhs - rhs);
}

export function normalizeFeatureSearchTileLevels(value: unknown): number[] {
    if (!Array.isArray(value)) {
        return [];
    }
    const seen = new Set<number>();
    const levels: number[] = [];
    for (const item of value) {
        const level = Number(item);
        if (!Number.isInteger(level)
            || level < MIN_FEATURE_SEARCH_TILE_LEVEL
            || level > MAX_FEATURE_SEARCH_TILE_LEVEL
            || seen.has(level)) {
            continue;
        }
        seen.add(level);
        levels.push(level);
    }
    return levels.sort((lhs, rhs) => lhs - rhs);
}

/** Normalizes the optional feature-type filter list; an empty list means any feature type. */
export function normalizeFeatureSearchFeatureTypes(value: unknown): string[] {
    if (!Array.isArray(value)) {
        return [];
    }
    const seen = new Set<string>();
    const types: string[] = [];
    for (const item of value) {
        const type = normalizeString(item);
        if (!type || seen.has(type)) {
            continue;
        }
        seen.add(type);
        types.push(type);
        if (types.length >= MAX_SELECTED_FEATURE_TYPES) {
            break;
        }
    }
    return types.sort((lhs, rhs) => lhs.localeCompare(rhs));
}

function normalizeSearchColorMode(raw: Record<string, unknown>): FeatureSearchColorMode {
    const nested = raw["color"];
    if (nested && typeof nested === "object" && !Array.isArray(nested)) {
        const color = nested as Record<string, unknown>;
        const mode = normalizeString(color["mode"]) ?? "solid";
        if (mode === "solid") {
            return {
                mode: "solid",
                color: normalizeHexColor(color["color"], DEFAULT_PIN_COLOR)
            };
        }
        if (mode === "gradient" || mode === "categories") {
            return {
                mode,
                field: normalizeString(color["field"]) ?? "",
                stops: normalizeColorStops(color["stops"]),
                ...(normalizeString(color["fallbackColor"])
                    ? {fallbackColor: normalizeHexColor(color["fallbackColor"], DEFAULT_PIN_COLOR)}
                    : {})
            };
        }
        if (!VALID_COLOR_MODES.has(mode)) {
            return {mode: "solid", color: DEFAULT_PIN_COLOR};
        }
    }

    const legacyExpression = normalizeString(raw["dataExpression"]) ?? "";
    const legacySolidColor = normalizeString(raw["solidColor"]);
    if (legacySolidColor) {
        return {mode: "solid", color: normalizeHexColor(legacySolidColor)};
    }
    const legacyGradient = normalizeColorStops(raw["gradient"]);
    if (legacyGradient.length) {
        return {mode: "gradient", field: legacyExpression, stops: legacyGradient};
    }
    const legacyColorMap = normalizeColorStops(raw["colorMap"]);
    if (legacyColorMap.length) {
        return {mode: "categories", field: legacyExpression, stops: legacyColorMap};
    }
    return {mode: "solid", color: DEFAULT_PIN_COLOR};
}

function normalizePositiveNumber(value: unknown, min = 0): number | undefined {
    const numberValue = Number(value);
    return Number.isFinite(numberValue) && numberValue >= min ? numberValue : undefined;
}

export function normalizeFeatureSearchRenderStrategy(value: unknown): FeatureSearchRenderStrategy {
    if (!value || typeof value !== "object" || Array.isArray(value)) {
        return {...DEFAULT_FEATURE_SEARCH_RENDER_STRATEGY};
    }
    const raw = value as Record<string, unknown>;
    const highFidelityMaxVisibleTiles = normalizePositiveNumber(
        raw["highFidelityMaxVisibleTiles"],
        MIN_HIGH_FIDELITY_VISIBLE_TILES
    );
    const densitySizeMultiplier = normalizePositiveNumber(
        raw["densitySizeMultiplier"],
        MIN_DENSITY_SIZE_MULTIPLIER
    );
    return {
        showLowFiDots: normalizeBoolean(
            raw["showLowFiDots"],
            DEFAULT_FEATURE_SEARCH_RENDER_STRATEGY.showLowFiDots
        ),
        showBucketLabels: normalizeBoolean(
            raw["showBucketLabels"],
            DEFAULT_FEATURE_SEARCH_RENDER_STRATEGY.showBucketLabels
        ),
        showHighFiGeometry: normalizeBoolean(
            raw["showHighFiGeometry"],
            DEFAULT_FEATURE_SEARCH_RENDER_STRATEGY.showHighFiGeometry
        ),
        showHighFiResultDots: normalizeBoolean(
            raw["showHighFiResultDots"],
            DEFAULT_FEATURE_SEARCH_RENDER_STRATEGY.showHighFiResultDots
        ),
        highFidelityMaxVisibleTiles: Math.min(
            MAX_HIGH_FIDELITY_VISIBLE_TILES,
            Math.max(
                MIN_HIGH_FIDELITY_VISIBLE_TILES,
                Math.floor(highFidelityMaxVisibleTiles
                    ?? DEFAULT_FEATURE_SEARCH_RENDER_STRATEGY.highFidelityMaxVisibleTiles)
            )
        ),
        densityHeatGradient: normalizeBoolean(
            raw["densityHeatGradient"],
            DEFAULT_FEATURE_SEARCH_RENDER_STRATEGY.densityHeatGradient
        ),
        densitySizeMultiplier: Math.min(
            MAX_DENSITY_SIZE_MULTIPLIER,
            Math.max(
                MIN_DENSITY_SIZE_MULTIPLIER,
                densitySizeMultiplier ?? DEFAULT_FEATURE_SEARCH_RENDER_STRATEGY.densitySizeMultiplier
            )
        )
    };
}

function normalizeStyleRule(value: unknown): FeatureSearchStyleRule | null {
    if (!value || typeof value !== "object" || Array.isArray(value)) {
        return null;
    }
    const raw = value as Record<string, unknown>;
    const width = normalizePositiveNumber(raw["width"]);
    const pointRadius = normalizePositiveNumber(raw["pointRadius"]);
    const opacity = normalizePositiveNumber(raw["opacity"]);
    const labelExpression = normalizeString(raw["labelExpression"] ?? raw["labelField"] ?? raw["label"]);
    const labelBackgroundColor = raw["labelBackgroundColor"] === undefined
        ? undefined
        : normalizeHexColor(raw["labelBackgroundColor"], DEFAULT_FEATURE_SEARCH_LABEL_BACKGROUND_COLOR);
    return {
        ...(normalizeString(raw["name"]) ? {name: normalizeString(raw["name"])} : {}),
        ...(normalizeBoolean(raw["autoGenerated"], false) ? {autoGenerated: true} : {}),
        geometry: normalizeGeometry(raw["geometry"] ?? raw["type"]),
        filter: normalizeRuleFilters(raw["filter"]),
        color: normalizeSearchColorMode(raw),
        ...(width !== undefined ? {width} : {}),
        ...(pointRadius !== undefined ? {pointRadius} : {}),
        ...(opacity !== undefined ? {opacity: Math.min(opacity, 1)} : {}),
        ...(labelExpression ? {labelExpression} : {}),
        ...(normalizeBoolean(raw["labelCustomExpression"], false) ? {labelCustomExpression: true} : {}),
        ...(labelBackgroundColor ? {labelBackgroundColor} : {})
    };
}

export function normalizeFeatureSearchStateEntry(value: unknown): FeatureSearchStateEntry | null {
    if (!value || typeof value !== "object" || Array.isArray(value)) {
        return null;
    }
    const raw = value as Record<string, unknown>;
    const query = normalizeString(raw["query"]);
    if (!query) {
        return null;
    }
    const id = normalizeString(raw["id"]) ?? createFeatureSearchId();
    const selectedMapLayers = normalizeSearchMapLayerRefs(raw["selectedMapLayers"]);
    const styleRules = Array.isArray(raw["searchStyleRules"])
        ? raw["searchStyleRules"]
            .slice(0, MAX_STYLE_RULES_PER_SEARCH)
            .map(normalizeStyleRule)
            .filter((rule): rule is FeatureSearchStyleRule => !!rule)
        : [];
    return {
        id,
        query,
        scope: normalizeScope(raw["scope"]),
        autoUpdate: normalizeBoolean(raw["autoUpdate"], true),
        bookmarked: normalizeBoolean(raw["bookmarked"], false),
        enabled: normalizeBoolean(raw["enabled"], true),
        paused: normalizeBoolean(raw["paused"], false),
        showResultsOnMap: normalizeBoolean(raw["showResultsOnMap"], true),
        pinColor: normalizeHexColor(raw["pinColor"]),
        selectedMapLayers,
        selectedMapLayersManual: normalizeBoolean(raw["selectedMapLayersManual"], false),
        selectedFeatureTypes: normalizeFeatureSearchFeatureTypes(raw["selectedFeatureTypes"]),
        selectedTileLevels: normalizeFeatureSearchTileLevels(raw["selectedTileLevels"]),
        selectedViewIndices: normalizeSearchViewIndices(raw["selectedViewIndices"]),
        searchStyleRules: styleRules,
        renderStrategy: normalizeFeatureSearchRenderStrategy(raw["renderStrategy"])
    };
}

export function normalizeFeatureSearchState(value: unknown): FeatureSearchStateEntry[] {
    if (!Array.isArray(value)) {
        return [];
    }
    const seenIds = new Set<string>();
    const result: FeatureSearchStateEntry[] = [];
    for (const rawEntry of value.slice(0, MAX_FEATURE_SEARCHES)) {
        const entry = normalizeFeatureSearchStateEntry(rawEntry);
        if (!entry) {
            continue;
        }
        while (seenIds.has(entry.id)) {
            entry.id = createFeatureSearchId();
        }
        seenIds.add(entry.id);
        result.push(entry);
    }
    return result;
}

export function featureSearchVisibleInView(
    definition: Pick<FeatureSearchStateEntry, "selectedViewIndices">,
    viewIndex: number
): boolean {
    const selectedViewIndices = Array.isArray(definition.selectedViewIndices)
        ? definition.selectedViewIndices
        : DEFAULT_FEATURE_SEARCH_VIEW_INDICES;
    return selectedViewIndices.includes(viewIndex);
}

/**
 * Derives the default result views for a search from the selected map/layers.
 * Falls back to every currently supported view when no selected layer is enabled in any view.
 */
export function defaultFeatureSearchViewIndicesForMapLayers(
    selectedMapLayers: FeatureSearchMapLayerRef[],
    numViews: number,
    layerVisibleInView: (viewIndex: number, ref: FeatureSearchMapLayerRef) => boolean
): number[] {
    const supportedViewCount = Math.max(
        0,
        Math.min(MAX_SUPPORTED_FEATURE_SEARCH_VIEWS, Math.floor(numViews))
    );
    const fallback = DEFAULT_FEATURE_SEARCH_VIEW_INDICES
        .filter(viewIndex => viewIndex < supportedViewCount);
    if (!selectedMapLayers.length) {
        return fallback;
    }

    const viewIndices = new Set<number>();
    for (let viewIndex = 0; viewIndex < supportedViewCount; ++viewIndex) {
        if (selectedMapLayers.some(ref => layerVisibleInView(viewIndex, ref))) {
            viewIndices.add(viewIndex);
        }
    }
    return viewIndices.size
        ? Array.from(viewIndices).sort((lhs, rhs) => lhs - rhs)
        : fallback;
}

export function createFeatureSearchStateEntry(value: {query: string} & Partial<FeatureSearchStateEntry>): FeatureSearchStateEntry {
    return normalizeFeatureSearchStateEntry({
        id: createFeatureSearchId(),
        scope: "auto",
        autoUpdate: true,
        bookmarked: false,
        enabled: true,
        paused: false,
        showResultsOnMap: true,
        pinColor: DEFAULT_PIN_COLOR,
        selectedMapLayers: [],
        selectedMapLayersManual: false,
        selectedFeatureTypes: [],
        selectedTileLevels: [...DEFAULT_FEATURE_SEARCH_TILE_LEVELS],
        selectedViewIndices: [...DEFAULT_FEATURE_SEARCH_VIEW_INDICES],
        searchStyleRules: [],
        renderStrategy: DEFAULT_FEATURE_SEARCH_RENDER_STRATEGY,
        ...value
    })!;
}

export function serializeFeatureSearchState(value: FeatureSearchStateEntry[]): FeatureSearchStateEntry[] {
    return normalizeFeatureSearchState(value);
}
