import {describe, expect, it} from "vitest";

import {
    detachSearchStyleRules,
    normalizeSearchStyleConfigurationState
} from "./search-style-configuration-state";

describe("SearchStyleConfigurationState", () => {
    it("keeps only high-fidelity rules while preserving per-rule layer applicability", () => {
        const state = normalizeSearchStyleConfigurationState({
            schemaVersion: 99,
            configurations: [{
                id: "saved",
                revision: 3,
                name: "  Roads  ",
                query: "typeId == 'Road'",
                scope: "attribute",
                selectedMapLayers: [{mapId: "ignored", layerId: "ignored"}],
                rules: [{
                    autoGenerated: true,
                    geometry: "polygon",
                    mapLayers: [{mapId: "Map A", layerId: "Roads"}],
                    filter: [{
                        field: "properties.speed > 10",
                        op: "=",
                        value: true,
                        customExpression: true
                    }],
                    color: {
                        mode: "gradient",
                        field: "properties.speed * 2",
                        customField: true,
                        stops: [{value: 1, color: "#ABC"}]
                    }
                }]
            }]
        });

        expect(state.schemaVersion).toBe(1);
        expect(state.configurations[0].name).toBe("Roads");
        expect(state.configurations[0]).not.toHaveProperty("query");
        expect(state.configurations[0]).not.toHaveProperty("scope");
        expect(state.configurations[0].rules[0]).not.toHaveProperty("autoGenerated");
        expect(state.configurations[0].rules[0].mapLayers).toEqual([
            {mapId: "Map A", layerId: "Roads"}
        ]);
        expect(state.configurations[0].rules[0].filter[0].customExpression).toBe(true);
        expect(state.configurations[0].rules[0].color).toMatchObject({customField: true});
    });

    it("returns deeply detached rule copies", () => {
        const source = [{
            geometry: "line",
            filter: [{field: "speed", op: ">", value: 30}],
            color: {mode: "solid", color: "#123456"},
            mapLayers: [{mapId: "Map", layerId: "Layer"}]
        }];

        const first = detachSearchStyleRules(source);
        const second = detachSearchStyleRules(first);
        first[0].filter[0].field = "changed";
        first[0].mapLayers![0].mapId = "changed";

        expect(second[0].filter[0].field).toBe("speed");
        expect(second[0].mapLayers![0].mapId).toBe("Map");
    });

    it("repairs duplicate persisted display names deterministically", () => {
        const state = normalizeSearchStyleConfigurationState({
            configurations: [
                {id: "one", name: "Roads", rules: []},
                {id: "two", name: "roads", rules: []},
                {id: "three", name: "Roads", rules: []}
            ]
        });

        expect(state.configurations.map(configuration => configuration.name)).toEqual([
            "Roads",
            "roads 2",
            "Roads 3"
        ]);
    });
});
