import {z} from "zod";

import {
    FeatureSearchStyleRule,
    normalizeFeatureSearchStyleRules
} from "./feature-search-state";

export const SEARCH_STYLE_CONFIGURATION_SCHEMA_VERSION = 1 as const;
export const MAX_SEARCH_STYLE_CONFIGURATIONS = 100;
export const MAX_SEARCH_STYLE_CONFIGURATION_NAME_LENGTH = 128;
export const MAX_SEARCH_STYLE_CONFIGURATION_BYTES = 512 * 1024;
export const MAX_SEARCH_STYLE_CONFIGURATION_STATE_BYTES = 2 * 1024 * 1024;

/** One reusable, scope-independent collection of high-fidelity search rules. */
export interface SearchStyleConfigurationV1 {
    id: string;
    revision: number;
    name: string;
    rules: FeatureSearchStyleRule[];
    createdAt: string;
    updatedAt: string;
}

/** Versioned non-URL AppState payload for reusable search style configurations. */
export interface SearchStyleConfigurationStateV1 {
    schemaVersion: typeof SEARCH_STYLE_CONFIGURATION_SCHEMA_VERSION;
    configurations: SearchStyleConfigurationV1[];
}

export const DEFAULT_SEARCH_STYLE_CONFIGURATION_STATE: SearchStyleConfigurationStateV1 = {
    schemaVersion: SEARCH_STYLE_CONFIGURATION_SCHEMA_VERSION,
    configurations: []
};

export const SearchStyleConfigurationStateSchema = z.unknown();

/** Creates a stable-enough local identifier without requiring browser UUID support. */
export function createSearchStyleConfigurationId(): string {
    const uuid = globalThis.crypto?.randomUUID?.();
    return uuid
        ? `search_style_${uuid}`
        : `search_style_${Date.now()}_${Math.random().toString(36).slice(2, 10)}`;
}

/** Returns a trimmed, bounded display name with a useful fallback. */
export function normalizeSearchStyleConfigurationName(value: unknown, fallback = "Search Style"): string {
    if (typeof value !== "string" || !value.trim()) {
        return fallback;
    }
    return value.trim().slice(0, MAX_SEARCH_STYLE_CONFIGURATION_NAME_LENGTH);
}

/** Makes the rule payload safe for a reusable configuration and strips runtime generation metadata. */
export function detachSearchStyleRules(value: unknown): FeatureSearchStyleRule[] {
    return normalizeFeatureSearchStyleRules(value).map(rule => {
        const copy = {...rule};
        delete copy.autoGenerated;
        return copy;
    });
}

/** Normalizes a persisted configuration collection and migrates unknown/legacy payloads defensively. */
export function normalizeSearchStyleConfigurationState(value: unknown): SearchStyleConfigurationStateV1 {
    const rawState = value && typeof value === "object" && !Array.isArray(value)
        ? value as Record<string, unknown>
        : {};
    const rawConfigurations = Array.isArray(rawState["configurations"])
        ? rawState["configurations"]
        : Array.isArray(value) ? value : [];
    const configurations: SearchStyleConfigurationV1[] = [];
    const seenIds = new Set<string>();
    const seenNames = new Set<string>();

    for (const item of rawConfigurations.slice(0, MAX_SEARCH_STYLE_CONFIGURATIONS)) {
        if (!item || typeof item !== "object" || Array.isArray(item)) {
            continue;
        }
        const raw = item as Record<string, unknown>;
        let id = typeof raw["id"] === "string" && raw["id"].trim()
            ? raw["id"].trim()
            : createSearchStyleConfigurationId();
        while (seenIds.has(id)) {
            id = createSearchStyleConfigurationId();
        }
        seenIds.add(id);
        const now = new Date().toISOString();
        const createdAt = normalizeTimestamp(raw["createdAt"], now);
        const name = uniqueNormalizedName(raw["name"], seenNames);
        const configuration: SearchStyleConfigurationV1 = {
            id,
            revision: normalizeRevision(raw["revision"]),
            name,
            rules: detachSearchStyleRules(raw["rules"]),
            createdAt,
            updatedAt: normalizeTimestamp(raw["updatedAt"], createdAt)
        };
        if (serializedByteLength(configuration) > MAX_SEARCH_STYLE_CONFIGURATION_BYTES) {
            seenIds.delete(id);
            seenNames.delete(name.toLocaleLowerCase());
            continue;
        }
        const candidate = [...configurations, configuration];
        if (!searchStyleConfigurationStateFits(candidate)) {
            break;
        }
        configurations.push(configuration);
    }

    return {
        schemaVersion: SEARCH_STYLE_CONFIGURATION_SCHEMA_VERSION,
        configurations
    };
}

/** Checks the aggregate local-library budget before a CRUD operation mutates AppState. */
export function searchStyleConfigurationStateFits(
    configurations: readonly SearchStyleConfigurationV1[]
): boolean {
    return configurations.every(configuration =>
        serializedByteLength(configuration) <= MAX_SEARCH_STYLE_CONFIGURATION_BYTES)
        && serializedByteLength({
            schemaVersion: SEARCH_STYLE_CONFIGURATION_SCHEMA_VERSION,
            configurations
        }) <= MAX_SEARCH_STYLE_CONFIGURATION_STATE_BYTES;
}

/** Produces the compact, normalized AppState storage representation. */
export function serializeSearchStyleConfigurationState(
    value: SearchStyleConfigurationStateV1
): SearchStyleConfigurationStateV1 {
    return normalizeSearchStyleConfigurationState(value);
}

function uniqueNormalizedName(value: unknown, seenNames: Set<string>): string {
    const requested = normalizeSearchStyleConfigurationName(value);
    let name = requested;
    let suffix = 2;
    while (seenNames.has(name.toLocaleLowerCase())) {
        const ending = ` ${suffix++}`;
        name = `${requested.slice(0, MAX_SEARCH_STYLE_CONFIGURATION_NAME_LENGTH - ending.length)}${ending}`;
    }
    seenNames.add(name.toLocaleLowerCase());
    return name;
}

function normalizeRevision(value: unknown): number {
    const revision = Number(value);
    return Number.isInteger(revision) && revision > 0 ? revision : 1;
}

function normalizeTimestamp(value: unknown, fallback: string): string {
    if (typeof value !== "string" || !value.trim()) {
        return fallback;
    }
    const parsed = Date.parse(value);
    return Number.isFinite(parsed) ? new Date(parsed).toISOString() : fallback;
}

function serializedByteLength(value: unknown): number {
    try {
        return new TextEncoder().encode(JSON.stringify(value)).byteLength;
    } catch {
        return Number.POSITIVE_INFINITY;
    }
}
