name: DefaultStyle
version: 1.0
options:
  - label: Show Meshes/Polygons
    id: showMesh
    default: false
  - label: Show Points
    id: showPoint
    default: true
  - label: Show Lines
    id: showLine
    default: true

rules:
  # Normal styles
  - geometry: ["mesh", "polygon"]
    filter: showMesh
    color: teal
    opacity: 0.8
    offset: [0, 0, -0.04]
  - geometry: ["line"]
    filter: showLine
    color: moccasin
    opacity: 1.0
    width: 5.0
    offset: [0, 0, -0.02]
  - geometry: ["point"]
    point-merge-grid-cell: [0.000000084, 0.000000084, 0.01]
    filter: showPoint
    color-expression: "$mergeCount > 1 and 'red' or 'moccasin'"
    label-text-expression: "$mergeCount > 1 and ($mergeCount as string) or ''"
    label-color: black
    label-font: "12px Helvetica"
    opacity: 1.0
    width: 15.0
    offset: [0, 0, -0.01]

  # Hover/Selection styles
  - geometry: ["mesh", "polygon"]
    color: green
    opacity: 0.8
    mode: hover
    offset: [0, 0, -0.03]
  - geometry: ["line"]
    color: green
    opacity: 0.8
    width: 10.0
    mode: hover
    offset: [0, 0, -0.01]
  - geometry: ["point"]
    color: green
    opacity: 0.8
    width: 20.0
    mode: hover
  - geometry: ["mesh", "polygon"]
    color: yellow
    opacity: 0.8
    mode: selection
    offset: [0, 0, -0.03]
  - geometry: ["line"]
    color: yellow
    opacity: 0.8
    width: 10.0
    mode: selection
    offset: [0, 0, -0.01]
  - geometry: ["point"]
    point-merge-grid-cell: [0.000000084, 0.000000084, 0.01]
    color: yellow
    opacity: 0.8
    width: 20.0
    mode: selection
