version: 1

presets:
  - id: lane-topology
    name: Lane Topology
    enabled: true
    layerAffinity: "^Lane$"
    values:
      - {styleId: NDS.Live/Lanes, optionId: showCenterLines, value: true}
      - {styleId: NDS.Live/Lanes, optionId: showDigitizationDir, value: true}
      - {styleId: NDS.Live/Lanes, optionId: showAdas, value: false}
      - {styleId: NDS.Live/Lanes, optionId: showZeroLengthLanes, value: true}
      - {styleId: NDS.Live/Lanes, optionId: showBoundaries, value: false}
      - {styleId: NDS.Live/Lanes, optionId: showGroups, value: false}
      - {styleId: NDS.Live/Lanes, optionId: showGroupConnectors, value: false}
      - {styleId: NDS.Live/Lanes, optionId: showTopology, value: true}

  - id: lane-group-topology
    name: Lane Group Topology
    enabled: true
    layerAffinity: "^Lane$"
    values:
      - {styleId: NDS.Live/Lanes, optionId: showCenterLines, value: false}
      - {styleId: NDS.Live/Lanes, optionId: showDigitizationDir, value: false}
      - {styleId: NDS.Live/Lanes, optionId: showAdas, value: false}
      - {styleId: NDS.Live/Lanes, optionId: showZeroLengthLanes, value: false}
      - {styleId: NDS.Live/Lanes, optionId: showBoundaries, value: false}
      - {styleId: NDS.Live/Lanes, optionId: showGroups, value: true}
      - {styleId: NDS.Live/Lanes, optionId: showGroupConnectors, value: true}
      - {styleId: NDS.Live/Lanes, optionId: showTopology, value: true}

  - id: lane-boundary
    name: Boundary
    enabled: true
    layerAffinity: "^Lane$"
    values:
      - {styleId: NDS.Live/Lanes, optionId: showCenterLines, value: false}
      - {styleId: NDS.Live/Lanes, optionId: showDigitizationDir, value: false}
      - {styleId: NDS.Live/Lanes, optionId: showAdas, value: false}
      - {styleId: NDS.Live/Lanes, optionId: showZeroLengthLanes, value: false}
      - {styleId: NDS.Live/Lanes, optionId: showBoundaries, value: true}
      - {styleId: NDS.Live/Lanes, optionId: showGroups, value: false}
      - {styleId: NDS.Live/Lanes, optionId: showGroupConnectors, value: false}
      - {styleId: NDS.Live/Lanes, optionId: showTopology, value: false}

  - id: lane-cinematic
    name: Lane Cinematic
    enabled: true
    layerAffinity: "^Lane$"
    values:
      - {styleId: NDS.Live/Lanes, optionId: showCenterLines, value: true}
      - {styleId: NDS.Live/Lanes, optionId: showDigitizationDir, value: false}
      - {styleId: NDS.Live/Lanes, optionId: showAdas, value: true}
      - {styleId: NDS.Live/Lanes, optionId: showZeroLengthLanes, value: false}
      - {styleId: NDS.Live/Lanes, optionId: showBoundaries, value: false}
      - {styleId: NDS.Live/Lanes, optionId: showGroups, value: false}
      - {styleId: NDS.Live/Lanes, optionId: showGroupConnectors, value: false}
      - {styleId: NDS.Live/Lanes, optionId: showTopology, value: false}

  - id: road-geometry
    name: Road Geometry
    enabled: true
    layerAffinity: "^Road$"
    values:
      - {styleId: NDS.Live/Roads, optionId: showRoadGeometries, value: true}
      - {styleId: NDS.Live/Roads, optionId: showDigitizationDir, value: false}
      - {styleId: NDS.Live/Roads, optionId: showRoadGeometriesAdas, value: false}
      - {styleId: NDS.Live/Roads, optionId: showIntersections, value: false}
      - {styleId: NDS.Live/Roads, optionId: showIndirectRoadGeometries, value: false}

  - id: road-direction
    name: Road Direction
    enabled: true
    layerAffinity: "^Road$"
    values:
      - {styleId: NDS.Live/Roads, optionId: showRoadGeometries, value: true}
      - {styleId: NDS.Live/Roads, optionId: showDigitizationDir, value: true}
      - {styleId: NDS.Live/Roads, optionId: showRoadGeometriesAdas, value: false}
      - {styleId: NDS.Live/Roads, optionId: showIntersections, value: false}
      - {styleId: NDS.Live/Roads, optionId: showIndirectRoadGeometries, value: false}

  - id: road-intersections
    name: Intersections
    enabled: true
    layerAffinity: "^Road$"
    values:
      - {styleId: NDS.Live/Roads, optionId: showRoadGeometries, value: false}
      - {styleId: NDS.Live/Roads, optionId: showDigitizationDir, value: false}
      - {styleId: NDS.Live/Roads, optionId: showRoadGeometriesAdas, value: false}
      - {styleId: NDS.Live/Roads, optionId: showIntersections, value: true}
      - {styleId: NDS.Live/Roads, optionId: showIndirectRoadGeometries, value: false}

  - id: road-cinematic
    name: Road Cinematic
    enabled: true
    layerAffinity: "^Road$"
    values:
      - {styleId: NDS.Live/Roads, optionId: showRoadGeometries, value: true}
      - {styleId: NDS.Live/Roads, optionId: showDigitizationDir, value: false}
      - {styleId: NDS.Live/Roads, optionId: showRoadGeometriesAdas, value: true}
      - {styleId: NDS.Live/Roads, optionId: showIntersections, value: false}
      - {styleId: NDS.Live/Roads, optionId: showIndirectRoadGeometries, value: false}
