import {createHash} from "node:crypto";
import {mkdirSync, writeFileSync} from "node:fs";
import {canonicalViewerContractJson, viewerActionCatalog, viewerJsonSchema} from "../app/actions/viewer-action.contract.js";
import {viewerActionClientMessageSchema, viewerActionServerMessageSchema, viewerMcpInfoSchema} from "../app/actions/viewer-action-relay.contract.js";

// This program imports only pure contract definitions. Never bootstrap Angular/WASM to export tools.
const catalog = viewerActionCatalog();
const canonical = canonicalViewerContractJson(catalog);
const catalogId = `sha256:${createHash("sha256").update(canonical, "utf8").digest("hex")}`;
const output = "app/actions/generated";
mkdirSync(output, {recursive: true});
writeFileSync(`${output}/viewer-actions.json`, `${JSON.stringify({...catalog, catalogId}, null, 2)}\n`);
writeFileSync(`${output}/viewer-actions.canonical.json`, canonical);
writeFileSync(`${output}/catalog-id.ts`, `// Generated by npm run generate:viewer-actions.\nexport const VIEWER_ACTION_CATALOG_ID = ${JSON.stringify(catalogId)};\n`);
writeFileSync(`${output}/viewer-action-relay.schema.json`, `${JSON.stringify({
    server: viewerJsonSchema(viewerActionServerMessageSchema),
    client: viewerJsonSchema(viewerActionClientMessageSchema),
    info: viewerJsonSchema(viewerMcpInfoSchema)
}, null, 2)}\n`);
console.log(`Viewer action catalog: ${catalogId}`);
