name: build-test

on:
  push:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure Git authentication for GitHub
        run: |
          git config --global url."https://x-access-token:${{ github.token }}@github.com/".insteadOf "https://github.com/"

      - name: Install build dependencies (ninja, git-lfs)
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build git-lfs

      - name: Initialize Git LFS
        run: git lfs install

      - name: Compile
        run: |
          cmake -S . -B build-test -GNinja -DCMAKE_BUILD_TYPE=Debug
          cmake --build build-test

      - name: Run Tests
        run: ctest --test-dir build-test --verbose --no-tests=error
